website/adminops/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'adminops'
urlpatterns = [
    path('', views.index, name='index'),
    path('pisetup', views.pisetup, name='pisetup'),
    path('piedit', views.piedit, name='piedit'),
    path('pilist', views.pilist, name='pilist'),
    path('pidelete', views.pidelete, name='pidelete'),
    path('piedit/feedersetup', views.feedersetup, name='feedersetup'),
    path('piedit/antennasetup', views.antennasetup, name='antennasetup'),
    path('piedit/feederdelete', views.feederdelete, name='feederdelete'),
    path('piedit/antennadelete', views.antennadelete, name='antennadelete'),
]

website/datalog/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'datalog'
urlpatterns = [
    path('', views.index, name='index'),
    path('rfiddata', views.index, name='rfiddata'),
    path('feedingdata', views.feedingdata, name='feedingdata'),
    path('RFIDcsv',views.getRfidFile, name = 'RFIDcsv'),
    path('completedTaskcsv',views.getCompletedTaskFile, name = 'completedTaskcsv'),    
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from elephants.views import index

urlpatterns = [
    path('', index),
    path('elephants/', include('elephants.urls', namespace='elephants')),
    path('admin/site/', admin.site.urls),
    path('admin/', include('adminops.urls', namespace='adminops')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('datalog/', include('datalog.urls')),
]

website/adminops/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

# Tentative Pi Connection Model
class Pi(models.Model):
    name = models.CharField(max_length=50, default="Pi") #name seen by users
    ip = models.GenericIPAddressField(protocol='IPv4', unique=True) #IPv4 address
    port = models.IntegerField(default=21,validators=[MinValueValidator(0), MaxValueValidator(65535)]) #port number
    connected = models.BooleanField(default=False)
    site_code = models.CharField(default="AAA", max_length=10, unique=True) #site code associated with reader box and antennas

    def __str__(self):
        return self.name + " " + str(self.id)
# Feeder Model
class Feeder(models.Model):
    name = models.CharField(max_length=50, default="Feeder") #name seen by users
    tag = models.CharField(max_length=10) #feeder tag
    connected_to = models.ForeignKey(Pi, on_delete=models.CASCADE) #pi connection
    pin = models.IntegerField(default=2,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(27)
        ]) # pin to activate this feeder

    def __str__(self):
        return self.name

# Antenna Model
class Antenna(models.Model):
    name = models.CharField(max_length=50, default="Antenna") #name seen by users
    tag = models.CharField(max_length=10) #antenna tag
    connected_to = models.ForeignKey(Pi, on_delete=models.CASCADE) #pi connection

    def __str__(self):
        return self.name

website/adminops/forms.py
from django.core.exceptions import ValidationError
from django.db.models.fields import IPAddressField, CharField
from django.forms import ModelForm, Field
from adminops.models import *

class PiForm(ModelForm):
    class Meta:
        model = Pi
        fields = ['name','ip', 'port', 'site_code']

class FeederForm(ModelForm):
    class Meta:
        model = Feeder
        fields = ['name','tag', 'pin']

class AntennaForm(ModelForm):
    class Meta:
        model = Antenna
        fields = ['name','tag']

website/adminops/views.py
# Views for the admin section of the site.
# Created by Luke Evers

from django.conf.urls import url
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.urls.conf import path
from adminops.models import *
from adminops.forms import *
from django.contrib.auth.views import *

@staff_member_required
def index(request):
    pis = Pi.objects.all()
    for pi in pis:
        pi.feeders = Feeder.objects.filter(connected_to=pi.id).count()
        pi.antennas = Antenna.objects.filter(connected_to=pi.id).count()
    return render(request, 'adminops/index.html', {"name": "Hungry Elephants Administration", "pis": pis})

@staff_member_required
def pisetup(request):
    if request.method == "POST":
        form = PiForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            pi = Pi()
            pi.name = request.POST["name"]
            pi.ip = request.POST["ip"]
            pi.port = request.POST["port"]
            pi.site_code = request.POST["site_code"]
            pi.save()
            return HttpResponseRedirect(reverse('adminops:index'))
    else:
        form = PiForm()
    return render(request, 'adminops/pisetup.html', {"name": "Hungry Elephants Administration", 'form': form})

# editing a pi
@staff_member_required
def piedit(request):
    if request.method == "POST":
        pi = Pi.objects.get(id=request.POST["id"])
        feeders = Feeder.objects.filter(connected_to=pi.id)
        antennas = Antenna.objects.filter(connected_to=pi.id)
        form = PiForm(request.POST, instance=pi)
        if form.is_valid():
            pi.name = request.POST["name"]
            pi.ip = request.POST["ip"]
            pi.port = request.POST["port"]
            pi.site_code = request.POST["site_code"]
            pi.save()
            return HttpResponseRedirect(reverse('adminops:index'))
    else:
        pi = Pi.objects.get(id=request.GET["id"])
        feeders = Feeder.objects.filter(connected_to=pi.id)
        antennas = Antenna.objects.filter(connected_to=pi.id)
        form = PiForm(instance=pi)
    return render(request, 'adminops/piedit.html', {"name": "Hungry Elephants Administration", "pi": pi, "form": form, "feeders": feeders, "antennas": antennas})

# view for returning ONLY the pi list
@staff_member_required
def pilist(request):
    pis = Pi.objects.all()
    for pi in pis:
        pi.feeders = str(len(Feeder.objects.filter(connected_to=pi.id)))
        pi.antennas = str(len(Antenna.objects.filter(connected_to=pi.id)))
    return render(request, 'adminops/pilist.html', {"name": "Hungry Elephants Administration", "pilist": pis})

# view for deleting a pi
@staff_member_required
def pidelete(request):
    pi = Pi.objects.get(id=request.GET["id"])
    pi.delete()
    pis = Pi.objects.all()
    return redirect(reverse('adminops:index'), {"name": "Hungry Elephants Administration", "pilist": pis})

# view for adding a feeder to a pi
@staff_member_required
def feedersetup(request):
    if request.method == "POST":
        form = FeederForm(request.POST)
        if form.is_valid():
            pi = Pi.objects.get(id=request.POST["pid"])
            feeder = Feeder()
            feeder.name = request.POST["name"]
            if((len(request.POST["tag"])>0) and (request.POST["tag"][0].upper()=="F")):
                tag = "F" + request.POST["tag"][1:]
            else:
                tag = "F" + request.POST["tag"]
            feeder.tag = tag
            feeder.connected_to = pi
            feeder.pin = request.POST["pin"]
            feeder.save()
            return redirect("/admin/piedit?id="+str(pi.id))
    else:
        pi = Pi.objects.get(id=request.GET["pid"])
        form = FeederForm(request.POST)
        if "fid" in request.GET:
            feeder = Feeder.objects.get(id=request.GET["fid"])
            form.initial = {"name": feeder.name, "tag": feeder.tag}
            return render(request, 'adminops/feedersetup.html', {"name": "Hungry Elephants Administration", "pi": pi, "feeder": feeder, "form": form})
        else:
            return render(request, 'adminops/feedersetup.html', {"name": "Hungry Elephants Administration", "pi": pi, "form": form})
    

# view for adding an antenna to a pi
@staff_member_required
def antennasetup(request):
    if request.method == "POST":
        form = AntennaForm(request.POST)
        if form.is_valid():
            pi = Pi.objects.get(id=request.POST["pid"])
            antenna = Antenna()
            antenna.name = request.POST["name"]
            antenna.tag = request.POST["tag"]
            antenna.connected_to = pi
            antenna.save()
            return redirect("/admin/piedit?id="+str(pi.id))
    else:
        pi = Pi.objects.get(id=request.GET["pid"])
        form = AntennaForm(request.POST)
        if "fid" in request.GET:
            antenna = Antenna.objects.get(id=request.GET["aid"])
            form.initial = {"name": antenna.name, "tag": antenna.tag}
            return render(request, 'adminops/antennasetup.html', {"name": "Hungry Elephants Administration", "pi": pi, "antenna": antenna, "form": form})
        else:
            return render(request, 'adminops/antennasetup.html', {"name": "Hungry Elephants Administration", "pi": pi, "form": form})

# delete a feeder
@staff_member_required
def feederdelete(request):
    pi = Pi.objects.get(id=request.GET["pid"])
    feeder = Feeder.objects.get(id=request.GET["id"])
    feeder.delete()
    return redirect("/admin/piedit?id="+str(pi.id))

# delete an antenna
@staff_member_required
def antennadelete(request):
    pi = Pi.objects.get(id=request.GET["pid"])
    antenna = Antenna.objects.get(id=request.GET["id"])
    antenna.delete()
    return redirect("/admin/piedit?id="+str(pi.id))

# login view
class CustomLoginView(LoginView):
    template_name = "registration/login.html"
    extra_context = {'next':'/elephants/'}
    
# logout view
class CustomLogoutView(LogoutView):
    template_name = "registration/logout.html"
    next_page = '/accounts/login'

# password reset view
class CustomPasswordResetView(PasswordResetView):
    template_name = "registration/passwordreset.html"

website/adminops/templates/adminops/antennalist.html
{% load static %}
{% url 'adminops:antennadelete' as antennadelete_url %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Antenna Name</th>
            <th scope="col">Tag</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for antenna in antennas %}
            <tr>
                <td>{{ antenna.name }}</td>
                <td>{{ antenna.tag }}</td>
                <td class="float-right">
                    <div class="row">
                        <div class="col">
                            <a class="btn btn-danger" href="{{ antennadelete_url }}?pid={{ pi.id }}&id={{ antenna.id }}">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

website/adminops/templates/adminops/antennasetup.html
{% extends "adminops/base.html" %}
{% load static %}

{% block content %}

<!-- set URLs -->
{% url 'adminops:index' as admin_url %}
{% url 'adminops:piedit' as piedit_url %}
{% url 'admin:index' as siteadmin_url %}
{% url 'adminops:pisetup' as pisetup_url %}
{% url 'adminops:antennasetup' as antennasetup_url %}

<div class="container p-3">
    <h1 class="display-4 text-center">Administration</h1>
    <div class="text-center">
        <a href="{{ admin_url }}" class="btn btn-link bg-light font-weight-bold">Administration Home</a>
        <a href="{{ siteadmin_url }}" class="btn btn-link bg-light">Site Administration</a>
    </div>
</div>

<div class="container">
    <p class="text-center">
        <a href="{{ piedit_url }}?id={{ pi.id }}" class="btn btn-secondary">Go Back</a>
    </p>
</div>

<div class="container">
    <form action="{{ antennasetup_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" id="pid" name="pid" value="{{ pi.id }}">
        <input type="submit" value="Submit">
    </form>
</div>


<!-- Set the pageurl variable to be passed to the JS -->
<script>
    var pageurl = "/admin/";
</script>

{% endblock content %}

website/adminops/templates/adminops/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {{name}}
        </title>
        {% include "adminops/bootstrap.html" %}
    </head>
    <body>
        {% include "elephants/navbar.html" %}
        {% block content %}
        {% endblock %}
        <script src="{% static 'adminops/nav.js' %}"></script>
    </body>
</html>

website/adminops/templates/adminops/bootstrap.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src = "{% static 'elephants/index.js' %}"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600,700" rel="stylesheet" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

website/adminops/templates/adminops/feederlist.html
{% load static %}
{% url 'adminops:feederdelete' as feederdelete_url %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Feeder Name</th>
            <th scope="col">Tag</th>
            <th scope="col">Pin</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for feeder in feeders %}
            <tr>
                <td>{{ feeder.name }}</td>
                <td>{{ feeder.tag }}</td>
                <td>{{ feeder.pin }}</td>
                <td class="float-right">
                    <div class="row">
                        <div class="col">
                            <a class="btn btn-danger" href="{{ feederdelete_url }}?pid={{ pi.id }}&id={{ feeder.id }}">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

website/adminops/templates/adminops/feedersetup.html
{% extends "adminops/base.html" %}
{% load static %}

{% block content %}

<!-- set URLs -->
{% url 'adminops:index' as admin_url %}
{% url 'adminops:piedit' as piedit_url %}
{% url 'admin:index' as siteadmin_url %}
{% url 'adminops:pisetup' as pisetup_url %}
{% url 'adminops:feedersetup' as feedersetup_url %}

<div class="container p-3">
    <h1 class="display-4 text-center">Administration</h1>
    <div class="text-center">
        <a href="{{ admin_url }}" class="btn btn-link bg-light font-weight-bold">Administration Home</a>
        <a href="{{ siteadmin_url }}" class="btn btn-link bg-light">Site Administration</a>
    </div>
</div>

<div class="container">
    <p class="text-center">
        <a href="{{ piedit_url }}?id={{ pi.id }}" class="btn btn-secondary">Go Back</a>
    </p>
</div>

<div class="container">
    <p>Feeder tags must start with an <b>F</b>. If it does not start with an F, one will be added for you.</p>
    <form action="{{ feedersetup_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" id="pid" name="pid" value="{{ pi.id }}">
        <input type="submit" value="Submit">
    </form>
</div>


<!-- Set the pageurl variable to be passed to the JS -->
<script>
    var pageurl = "/admin/";
</script>

{% endblock content %}

website/adminops/templates/adminops/index.html
{% extends "adminops/base.html" %}
{% load static %}

{% block content %}

<!-- set URLs -->
{% url 'logout' as logout_url %}
{% url 'adminops:index' as admin_url %}
{% url 'admin:index' as siteadmin_url %}
{% url 'adminops:pisetup' as pisetup_url %}
{% url 'adminops:pilist' as pirefresh_url %}
{% url 'adminops:piedit' as piedit_url %}
{% url 'adminops:pidelete' as pidelete_url %}

<div class="container">
    <br>
    <div class="jumbotron">
        <h1 class="text-center">Administration</h1>
    </div>
</div>
    <div class="container text-center">
        <a href="{{ admin_url }}" class="btn btn-link bg-light">Administration Home</a>
        <a href="{{ siteadmin_url }}" class="btn btn-link bg-light">Site Administration</a>
    </div>
    <br>
<div class="container">
    <p class="text-center">
        <a href="{{ pisetup_url }}" class="btn btn-primary">Connect a Raspberry Pi</a>
    </p>
    <p class="text-center">
        <a class="btn btn-primary" id="refresh" href="{{ admin_url }}">Refresh</a>
    </p>
    <div>
        {% include "adminops/pilist.html" %}
    </div>
</div>

<!--img src="{% static 'adminops/test.png' %}"-->

<!-- Set the pageurl variable to be passed to the JS -->
<script>
    var pageurl = "{{ request.path }}";
</script>

{% endblock %}

website/adminops/templates/adminops/piedit.html
{% extends "adminops/base.html" %}
{% load static %}

{% block content %}

<!-- set URLs -->
{% url 'adminops:index' as admin_url %}
{% url 'admin:index' as siteadmin_url %}
{% url 'adminops:pisetup' as pisetup_url %}
{% url 'adminops:piedit' as piedit_url %}
{% url 'adminops:feedersetup' as feedersetup_url %}
{% url 'adminops:antennasetup' as antennasetup_url %}

<div class="container p-3">
    <h1 class="display-4 text-center">Administration</h1>
    <div class="text-center">
        <a href="{{ admin_url }}" class="btn btn-link bg-light font-weight-bold">Administration Home</a>
        <a href="{{ siteadmin_url }}" class="btn btn-link bg-light">Site Administration</a>
    </div>
</div>

<div class="container">
    <p class="text-center">
        <a href="{{ admin_url }}" class="btn btn-secondary">Go Back</a>
    </p>
</div>

<table class="table container">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Site Code</th>
            <th scope="col">IP</th>
            <th scope="col">Port</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ pi.name }}</td>
            <td>{{ pi.site_code }}</td>
            <td>{{ pi.ip }}</td>
            <td>{{ pi.port }}</td>
            {% if pi.connected %}
                <td class="text-success">Connected</td>
            {% else %}
                <td class="text-danger">Not Connected</td>
            {% endif %}
            <td class="float-right">
                <div class="row">
                    <div class="col">
                        <!-- TODO: use JS to ask if user is sure -->
                        <a class="btn btn-danger" href="{{ pidelete_url }}?id={{ pi.id }}">Delete</a>
                    </div>
                </div>
            </td>
        </tr>
    </tbody>
</table>

<div class="container">
    <p class="text-center">Edit this pi:</p>
    <form action="{{ piedit_url }}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" name="id" value="{{pi.id}}">
        <input type="submit" value="Submit">
    </form>
</div>

<div class="container p-3">
    {% include 'adminops/feederlist.html' %}
</div>

<div class="container p-3">
    {% include 'adminops/antennalist.html' %}
</div>

<div class="container text-center">
    <p>Make connections with this pi:</p>
    <a href="{{ feedersetup_url }}?pid={{ pi.id }}" class="btn btn-primary">Add a Feeder</a>
    <a href="{{ antennasetup_url }}?pid={{ pi.id }}" class="btn btn-primary">Add an Antenna</a>
</div>


<!-- Set the pageurl variable to be passed to the JS -->
<script>
    var pageurl = "/admin/";
</script>

{% endblock content %}

website/adminops/templates/adminops/pilist.html
{% load static %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Site Code</th>
            <th scope="col">IP</th>
            <th scope="col">Port</th>

            <th scope="col">Status</th>
            <th scope="col"># Feeders</th>
            <th scope="col"># Antennas</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for pi in pis %}
            <tr>
                <td>{{ pi.name }}</td>
                <td>{{ pi.site_code }}</td>
                <td>{{ pi.ip }}</td>
                <td>{{ pi.port }}</td>
                {% if pi.connected %}
                    <td class="text-success">Connected</td>
                {% else %}
                    <td class="text-danger">Not Connected</td>
                {% endif %}
                <td>{{ pi.feeders }}</td>
                <td>{{ pi.antennas }}</td>
                <td class="float-right">
                    <div class="row">
                        <div class="col">
                            <a class="btn btn-secondary" href="{{ piedit_url }}?id={{ pi.id }}">Edit</a>
                        </div>
                        <div class="col">
                            <!-- TODO: use JS to ask if user is sure -->
                            <a class="btn btn-danger" href="{{ pidelete_url }}?id={{ pi.id }}">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

website/adminops/templates/adminops/pisetup.html
{% extends "adminops/base.html" %}
{% load static %}

{% block content %}

<!-- set URLs -->
{% url 'adminops:index' as admin_url %}
{% url 'admin:index' as siteadmin_url %}
{% url 'adminops:pisetup' as pisetup_url %}

<div class="container p-3">
    <h1 class="display-4 text-center">Administration</h1>
    <div class="text-center">
        <a href="{{ admin_url }}" class="btn btn-link bg-light font-weight-bold">Administration Home</a>
        <a href="{{ siteadmin_url }}" class="btn btn-link bg-light">Site Administration</a>
    </div>
</div>

<div class="container">
    <p class="text-center">
        <a href="{{ admin_url }}" class="btn btn-secondary">Go Back</a>
    </p>
</div>

<div class="container">
    <form action="{{ pisetup_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>


<!-- Set the pageurl variable to be passed to the JS -->
<script>
    var pageurl = "/admin/";
</script>

{% endblock content %}