website/datalog/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'datalog'
urlpatterns = [
    path('', views.index, name='index'),
    path('rfiddata', views.index, name='rfiddata'),
    path('feedingdata', views.feedingdata, name='feedingdata'),
    path('RFIDcsv',views.getRfidFile, name = 'RFIDcsv'),
    path('completedTaskcsv',views.getCompletedTaskFile, name = 'completedTaskcsv'),    
]

website/elephants/urls.py
from django.urls import path

from . import views

#be sure to give every path a name variable so when we create links in the html templates we can reference these urls
app_name = 'elephants'

'''
These are the urls that return views

Since the app name is elephants, to get to the index page you'd go to /elephants
if you want to go to preset scheduling, you go to /elephants/presetscheduling
'''
urlpatterns = [
    path('', views.index, name='index'),
    path('feeders', views.feeders, name='feeders'),
    path('presetscheduling', views.preset_scheduling, name='presetscheduling'),
    path('custom', views.custom, name='custom'),
    path('presets', views.presets, name='presets'),
    path('schedule/', views.schedule, name='schedule'),
    path('editpreset', views.edit_preset_page, name='editpresetpage'),
    path('deletepresetschedule', views.delete_preset_schedule, name='deletepresetschedule'),
    path('launchpreset', views.execute_preset, name='executepreset'),
    path('activeschedules', views.active_schedules, name='activeschedules'),
    path('deleteschedulefromactive', views.delete_schedule_activeschedulepage, name="deleteschedulefromactive"),
    path('markinactivefromactive', views.mark_inactive_from_active, name="markinactivefromactive"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from elephants.views import index

urlpatterns = [
    path('', index),
    path('elephants/', include('elephants.urls', namespace='elephants')),
    path('admin/site/', admin.site.urls),
    path('admin/', include('adminops.urls', namespace='adminops')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('datalog/', include('datalog.urls')),
]

website/elephants/forms.py
from django.forms import ModelForm
from .models import Schedule, Elephant, PresetSchedule
from .models import Feeder
from django.db import models
from django.contrib.admin.widgets import AdminDateWidget
from django import forms
from datetime import datetime
from datetime import timedelta


#this a form for schedules
class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ('elephant', 'start_date','start_time', 'end_date', 'end_time', 'interval', 'max_feeds', 'feeder',)
        widgets = {
            'elephant': forms.Select(attrs={'class': 'form-control col-4'}),
            'start_time': forms.TimeInput(attrs={'class':'form-control col-4', 'type' : 'time'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control col-4', 'type' : 'date'}),
            'end_time': forms.TimeInput(attrs={'class': 'form-control col-4', 'type' : 'time'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control col-4','type' : 'date'}),
            'interval': forms.TextInput(attrs={'class': 'form-control col-4'}),
            'max_feeds': forms.NumberInput(attrs={'class': 'form-control col-4'}),
            'feeder': forms.Select(attrs={'class': 'form-control col-4'}),
        }

#this is basically the same as the schedule form but it doesn't include end and start date
class PresetForm(forms.ModelForm):
    class Meta:
        model = PresetSchedule
        fields = ('elephant', 'start_time', 'end_time', 'interval', 'max_feeds', 'feeder',)
        widgets = {
            'elephant': forms.Select(attrs={'class': 'form-control col-4'}),
            'start_time': forms.TimeInput(attrs={'class': 'form-control col-4', 'type' : 'time'}),
            'end_time': forms.TimeInput(attrs={'class': 'form-control col-4', 'type' : 'time'}),
            'interval': forms.TextInput(attrs={'class': 'form-control col-4'}),
            'max_feeds': forms.NumberInput(attrs={'class': 'form-control col-4'}),
            'feeder': forms.Select(attrs={'class': 'form-control col-4'}),
        }

website/elephants/views/POST.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from elephants.forms import ScheduleForm, PresetForm
from elephants.models import Schedule, Preset, Elephant, PresetSchedule
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from .view import edit_preset_page, edit_preset_page2, index
from django.contrib import messages


'''
This is a method that returns a Schedule form
and handles the form submission as well

if the form is valid, a schedule object will be 
created in the database
'''
def schedule(request):
    model = Schedule
    if request.method=='POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            sched = Schedule()
            sched.elephant = form.cleaned_data['elephant']
            sched.start_time = form.cleaned_data['start_time']
            sched.start_date = form.cleaned_data['start_date']
            sched.start_date_time = datetime.combine(sched.start_date, sched.start_time)
            sched.end_time = form.cleaned_data['end_time']
            sched.end_date = form.cleaned_data['end_date']
            sched.end_date_time = datetime.combine(sched.end_date, sched.end_time)
            sched.interval = 60 * form.cleaned_data['interval']
            sched.max_feeds = form.cleaned_data['max_feeds']
            sched.feeder = form.cleaned_data['feeder']
            sched.save()
            print("saved schedule")
            messages.info(request, "New schedule is activated")
            return index(request)
    else:
        form = ScheduleForm(initial={'start_time':'2021-03-18 17:30', 'end_time': '2021-03-18 18:00'})

    print("in normal scheduling module")
    return render(request, 'elephants/schedule_module.html', {'form':form})

'''
Same as the scheduling method but for preset schedule
'''
def preset_scheduling(request):
    if request.method=='POST':
        form = PresetForm(request.POST)
        if form.is_valid():
            currentDate = datetime.today().strftime('%Y-%m-%d')
            sched = Schedule()
            sched.elephant = form.cleaned_data['elephant']
            sched.start_time = form.cleaned_data['start_time'].strftime('%H:%M:%S')
            sched.start_date = currentDate
            new_st = sched.start_date+" "+sched.start_time
            sched.start_date_time = datetime.strptime(new_st, "%Y-%m-%d %H:%M:%S")

            sched.end_time = form.cleaned_data['end_time'].strftime('%H:%M:%S')
            sched.end_date = currentDate
            new_st = sched.end_date+" "+sched.end_time
            sched.end_date_time = datetime.strptime(new_st, "%Y-%m-%d %H:%M:%S")
            sched.interval = 60 * form.cleaned_data['interval']
            sched.max_feeds = form.cleaned_data['max_feeds']
            sched.feeder = form.cleaned_data['feeder']
            sched.active = False
            print("preset scheduling about to save")
            sched.save()
            sched.presets.add(Preset.objects.filter(pk=request.GET["id"])[0])
            sched.save()

            return edit_preset_page(request)
    else:
        form = PresetForm()

    print("in preset scheduling module")
    return render(request, 'elephants/preset_schedule_module.html', {'presetid':request.GET["id"], 'form':form})

website/elephants/views/database.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from elephants.forms import ScheduleForm, PresetForm
from elephants.models import Schedule, Preset, Elephant, PresetSchedule
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from .view import *
import pytz
from django.contrib import messages


est = pytz.timezone("US/Eastern")
central = pytz.timezone("America/Chicago")
'''this method should take schedules (from a preset) and update the date to
the current date and mark all of them as active'''
def create_active_preset_schedules(schedules):
    if(schedules):
        for s in schedules:
            print("original start time: "+str(s.start_time))
            print("original end time: "+str(s.end_time))
            new_start_time = (s.start_date_time.astimezone(central).time().strftime('%H:%M:%S'))
            new_end_time = s.end_date_time.astimezone(central).time().strftime('%H:%M:%S')
            print("new start time: "+new_start_time)
            print("new end time: "+str(new_end_time))
            currentDate = datetime.now(est).strftime('%Y-%m-%d')
            fullTime = currentDate+" "+new_start_time
            new_startDT = datetime.strptime(fullTime, "%Y-%m-%d %H:%M:%S")
            fullTime = currentDate+" "+new_end_time
            new_endDT = datetime.strptime(fullTime, "%Y-%m-%d %H:%M:%S")
            s.start_time_date = new_startDT
            s.end_time_date = new_endDT
            s.active = True
            s.save()

    print("preset schdules are updated!")


'''
Returns active schedules from the database
'''
def active_schedules(request):
    schedules = Schedule.objects.filter(active=True).order_by('-start_time')
    context = {'schedules' : schedules}
    return render(request, 'elephants/active_schedules.html', context)

'''
deletes a preset schedule
'''
def delete_preset_schedule(request):
    schedule = Schedule.objects.get(id=request.GET["id"])
    schedule.delete()
    return edit_preset_page2(request, request.GET["presetid"])

'''
deletes a schedule from the active schedule page
'''
def delete_schedule_activeschedulepage(request):
    delete_schedule(request.GET["id"])
    return active_schedules(request)


'''
deletes a schedule
'''
def delete_schedule(id):
    Schedule.objects.get(pk=id).delete()


'''
executes a preset
'''
def execute_preset(request):
    preset = Preset.objects.get(id=request.GET['id'])
    schedules = preset.schedule_set.all()
    create_active_preset_schedules(schedules)
    messages.info(request, "Preset " + str(preset.name) + " is activated")
    return index(request)

'''
marks a schedule as inactive and returns the active schedules page
'''
def mark_inactive_from_active(request):
    mark_inactive(request.GET["id"])
    return active_schedules(request)


'''
just marks a schedule as inactive
'''
def mark_inactive(id):
    schedule = Schedule.objects.get(pk=id)
    schedule.active = False
    schedule.save()

website/elephants/views/logic.py
from datalog.models import FeedingData
from elephants.models import Schedule
from datetime import datetime

import pytz
import time


est = pytz.timezone("US/Eastern")
utc = pytz.utc
fmt = "%Y-%m-%d %H:%M:%S"


'''
returns data for the home page tiles
'''
def elephantModuleData(elephant):
    erifd = elephant.rfid
    feedingDataQS = FeedingData.objects.filter(if_recieve_from_tag_number = erifd).order_by('-completed_time')
    feedingData = list()
    for fd in feedingDataQS:
        if(int(fd.completed_time)>=int(time.time())-84600):
            feedingData.append(fd)

    lastfed = "never"
    numberFeedingsToday =0
    endOfSchedule = "No Active Schedule"

    if(feedingData):
        lastfed = datetime.fromtimestamp(int(feedingData[0].completed_time), est).strftime("%Y-%m-%d %H:%M:%S")
        numberFeedingsToday = len(feedingData)

    activeSchedules =  Schedule.objects.filter(elephant=elephant).filter(active=True).order_by('-start_time')
    if(activeSchedules):
        endOfSchedule = activeSchedules[0].end_time

    return {"lastfed": lastfed, "feedingstoday": numberFeedingsToday, "currentscheduleends": endOfSchedule}

website/elephants/views/view.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from elephants.forms import ScheduleForm, PresetForm
from elephants.models import Schedule, Preset, Elephant, PresetSchedule
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from .logic import elephantModuleData
from django.contrib import messages


'''
This returns the index page (home page)
'''
def index(request):
    #get elephants from DB
    elephants = Elephant.objects.all()

    #this holds the data for the submodules on the home page
    elephantInfo = dict()
    for ele in elephants:
        #calling elephantModuleData returns the data associated with a given elephant (ele)
        elephantInfo[ele] = elephantModuleData(ele)

    #get 3 presets
    presets = Preset.objects.all()[:3]

    context = {'name': 'Hungry Elephants', 'elephantInfo': elephantInfo.items(), 'presets': presets}
    return render(request, 'elephants/index.html', context)

'''
Returns the feeders page
'''
def feeders(request):
    context = {'name': 'Feeders', }
    return render(request, 'elephants/feeders.html', context)
'''
Returns a test page
'''
def custom(request):
    context = {'name': 'Custom', }
    return render(request, 'elephants/custom.html', context)

'''
return the presets page
'''
def presets(request):
    context = {'name': 'Presets', }
    return render(request, 'elephants/presets.html', context)

'''
Return the page that lets you edit a preset
'''
def edit_preset_page(request):
    preset = Preset.objects.get(id=request.GET["id"])
    schedules = preset.schedule_set.all()
    context = {'preset': preset, 'schedules':schedules}
    return render (request, 'elephants/edit_preset.html', context)
    #bring up the edit preset page

#this is same as edit_preset_page but just takes an extra param, namely the presetid
def edit_preset_page2(request, id):
    preset = Preset.objects.get(id=id)
    schedules = preset.schedule_set.all()
    context = {'preset': preset, 'schedules':schedules}
    return render (request, 'elephants/edit_preset.html', context)
    #bring up the edit preset page

website/elephants/views/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from elephants.forms import ScheduleForm, PresetForm
from elephants.models import Schedule, Preset, Elephant, PresetSchedule
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime

def index(request):
    elephants = Elephant.objects.all()
    elephants1 = elephants[:3]
    elephants2 = elephants[3:]
    context = {'name': 'Hungry Elephants', 'elephants1': elephants1, 'elephants2':elephants2}
    return render(request, 'elephants/index.html', context)

def feeders(request):
    context = {'name': 'Feeders', }
    return render(request, 'elephants/feeders.html', context)

def custom(request):
    context = {'name': 'Custom', }
    return render(request, 'elephants/custom.html', context)

def presets(request):
    context = {'name': 'Presets', }
    return render(request, 'elephants/presets.html', context)

def edit_preset_page(request):
    preset = Preset.objects.get(id=request.GET["id"])
    schedules = preset.schedule_set.all()
    context = {'preset': preset, 'schedules':schedules}
    return render (request, 'elephants/edit_preset.html', context)
    #bring up the edit preset page

#this is same as edit_preset_page but just takes an extra param, namely the presetid
def edit_preset_page2(request, id):
    preset = Preset.objects.get(id=id)
    schedules = preset.schedule_set.all()
    context = {'preset': preset, 'schedules':schedules}
    return render (request, 'elephants/edit_preset.html', context)
    #bring up the edit preset page

website/elephants/templates/elephants/active_schedule_viewer_module.html
<div>
        <tr>
            <th scope="row">{{ schedule.id }}</th>
            <td>{{ schedule.elephant }}</td>
            <td>{{ schedule.start_time }}</td>
            <td>{{ schedule.end_time }}</td>
            <td>{{ schedule.interval }}</td>
            <td>{{ schedule.max_feeds }}</td>
            <td>{{ schedule.feeder }}</td>
            <td>
                <a href="/elephants/markinactivefromactive?id={{ schedule.id }}" class="btn btn-link">Mark Inactive</a>
            </td>
            <td>
                <a href="/elephants/deleteschedulefromactive?id={{ schedule.id }}" class="btn btn-link">Delete</a>
            </td>
        </tr>
</div>

website/elephants/templates/elephants/active_schedules.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    {% include "elephants/navbar.html" %}

    <br>
    <div class=container>
        <div class="jumbotron">
          <h1 class="text-center">Active Schedules</h1>
        </div>
    </div>

    <div class="container">
    <table class="table">
        <thread >
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Elephant</th>
                <th scope="col">Start Time</th>
                <th scope="col">End Time</th>
                <th scope="col">Interval</th>
                <th scope="col">Max Feeds</th>
                <th scope="col">Feeder</th>
            </tr>
        </thread>
        <tbody>
            {% for schedule in schedules %}
                {% include "elephants/active_schedule_viewer_module.html" with schedule=schedule %}
            {%endfor %}
        </tbody>
    </table>
    </div>
</body>
</html>

website/elephants/templates/elephants/default_schedule_selection.html
{% load static %}

{% url 'elephants:presetscheduling' as presetscheduling_url %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
{% include "elephants/navbar.html" %}

<div>
    <h1>Create New schedule from presets</h1>
    <table>
        <form action="{{ presetscheduling_url }}" method="post">
            {% csrf_token %}
            {{ selectpresetform.as_table }}
            <input type="submit" value="Submit">
        </form>
    </table>
</div>
<div style="height: 100px;">

</div>
<div>
    <h1>Mark Existing Schedules as preset</h1>
    <table class="table" style="width:50%; align-content: center; align:center">
        <thead>
            <tr>
                <th scope="col">Schedule Name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for schedule in non_defaults %}
            <tr>
                <td>{{ schedule.name }}</td>
                <td>
                    <button class = "btn btn-secondary">
                        <a href="/elephants/markpreset?id={{ schedule.id }}">
                            Add
                        </a>
                    </button>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>

website/elephants/templates/elephants/edit_preset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
{% include "elephants/navbar.html" %}
<body>

    <br>
    <div class=container>
        <div class="jumbotron">
          <h1 class="text-center">{{ preset.name }}</h1>
        </div>
    </div>

    <div class="container">
        <div>
            <a href="/elephants/presetscheduling?id={{ preset.id }}" class="btn btn-primary">Add New Schedule</a>
        </div>
        <br>
        <table class="table">
            <thread >
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Elephant</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Interval</th>
                    <th scope="col">Max Feeds</th>
                    <th scope="col">Feeder</th>
                    <th scope="col">Delete</th>
                </tr>
            </thread>
            <tbody>
                {% for schedule in schedules %}
                    {% include "elephants/preset_schedule_viewer_module.html" with schedule=schedule presetid=preset.id %}
                {%endfor %}
            </tbody>
        </table>
    </div>

</body>
</html>

website/elephants/templates/elephants/elephant_tile.html
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ elephant.name }}</h5>
          <p class="card-text">Last fed: {{data.lastfed}}<br>Number of feedings today: {{data.feedingstoday}}<br>Current Schedule Ends: {{data.currentscheduleends}}</p>
          <br>
        </div>
      </div>

website/elephants/templates/elephants/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{name}}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'elephants/index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src = "{% static 'elephants/index.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600,700" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>


<body>


    {% include "elephants/navbar.html" %}

    {% if messages %}
    <br>
    <div class="messages container">
      {% for message in messages %}
      <h4 class="text-center text-primary border border-primary"{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h4>
      {% endfor %}
    </div>
    {% endif %}

    <br>
    <div class=container>
      <div class="jumbotron">
        <h1 class="text-center">All Elephants</h1>
      </div>
    </div>

    <br>
    <div class="container">
      <div class="d-flex justify-content-center">
        <div class = "row">
            {% for preset in presets %}
            <div class ="col-2">
                <a href = "/elephants/launchpreset?id={{ preset.id}}" class ="btn btn-primary">{{preset.name}}</a>
            </div>
            <div class="col-2">
                <a href ="/elephants/editpreset?id={{preset.id}}" class = "btn btn-secondary">Edit</a>
            </div>
            {% endfor %}
        </div>
      </div>

    </div>



    <div class = container>
      <br>
        <div class="card-deck">
        {% for elephant, data in elephantInfo %}
                 {% include "elephants/elephant_tile.html" with elephant=elephant data=data %}
            {% if forloop.counter|divisibleby:2 %}
        </div>
        <br>
        <div class="card-deck">
            {% endif %}
        {% endfor %}
        </div>
    </div>
    
</body>
</html>

website/elephants/templates/elephants/navbar.html
<!-- set URLs -->
{% url 'elephants:scheduling' as scheduling_url %}
{% url 'elephants:preset_manager' as preset_manager_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/elephants">Home</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/elephants/schedule/">Scheduling</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/elephants/activeschedules">Active Schedules</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/datalog">Data Log</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/datalog/feedingdata">Completed Task</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/admin" id="adminlink">Admin</a>
        </li>
    </ul>
</nav>

website/elephants/templates/elephants/preset_schedule_module.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% include "elephants/navbar.html" %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<br>
<div class=container>
    <div class="jumbotron">
      <h1 class="text-center">Add a schedule</h1>
    </div>
</div>

<div class="container">
    <div class="form-group">
        <form action="/elephants/presetscheduling?id={{ presetid }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
</div>

website/elephants/templates/elephants/preset_schedule_viewer_module.html
<div>
        <tr>
            <th scope="row">{{ schedule.id }}</th>
            <td>{{ schedule.elephant }}</td>
            <td>{{ schedule.start_time|date:"P" }}</td>
            <td>{{ schedule.end_time|date:"P" }}</td>
            <td>{{ schedule.interval }}</td>
            <td>{{ schedule.max_feeds }}</td>
            <td>{{ schedule.feeder }}</td>
            <td>
                <a href="/elephants/deletepresetschedule?id={{ schedule.id }}&presetid={{presetid}}" class="btn btn-link">Delete</a>
            </td>
        </tr>
</div>

website/elephants/templates/elephants/schedule_module.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% url 'elephants:scheduling' as scheduling_url %}

{% include "elephants/navbar.html" %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<br>
<div class=container>
  <div class="jumbotron">
    <h1 class="text-center">Make a schedule</h1>
  </div>
</div>

{% if messages %}
<div class="messages container">
  {% for message in messages %}
  <h3 class="text-center text-primary"{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h3>
  {% endfor %}
</div>
{% endif %}

<div class="container">
    <div class="form-group">
        <form action="{{ scheduling_url }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
</div>